// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuA0ftBfYiFJ-bfB5GK8nfQNDrmfZRQFo',
    appId: '1:550838324209:web:a73696fbe9e4ed0ae61250',
    messagingSenderId: '550838324209',
    projectId: 'awp-iprocurement',
    authDomain: 'awp-iprocurement.firebaseapp.com',
    storageBucket: 'awp-iprocurement.firebasestorage.app',
    measurementId: 'G-9DJ99VVHM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBponhoRrFtnf8Cc8cfhqIdlKhKpybI_o',
    appId: '1:550838324209:android:0478d223156c3972e61250',
    messagingSenderId: '550838324209',
    projectId: 'awp-iprocurement',
    storageBucket: 'awp-iprocurement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZFBqqlepPHzxyxR9I-txBkfjHhM0fyw',
    appId: '1:550838324209:ios:e9cf0ce9e235ed83e61250',
    messagingSenderId: '550838324209',
    projectId: 'awp-iprocurement',
    storageBucket: 'awp-iprocurement.firebasestorage.app',
    iosBundleId: 'com.tm.iprocurement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZFBqqlepPHzxyxR9I-txBkfjHhM0fyw',
    appId: '1:550838324209:ios:e9cf0ce9e235ed83e61250',
    messagingSenderId: '550838324209',
    projectId: 'awp-iprocurement',
    storageBucket: 'awp-iprocurement.firebasestorage.app',
    iosBundleId: 'com.tm.iprocurement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuA0ftBfYiFJ-bfB5GK8nfQNDrmfZRQFo',
    appId: '1:550838324209:web:ee83326e868686a6e61250',
    messagingSenderId: '550838324209',
    projectId: 'awp-iprocurement',
    authDomain: 'awp-iprocurement.firebaseapp.com',
    storageBucket: 'awp-iprocurement.firebasestorage.app',
    measurementId: 'G-CX3WWVCZNF',
  );

}