// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6PhcW4rLWA8u1N5p79nRm2fqDMPmNZY',
    appId: '1:424900090253:web:2dff0e2f77d6e635bd45c4',
    messagingSenderId: '424900090253',
    projectId: 'aiman-hanif',
    authDomain: 'aiman-hanif.firebaseapp.com',
    storageBucket: 'aiman-hanif.firebasestorage.app',
    measurementId: 'G-4V8PE10SB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC149GZn00WTlwKS45m4rn8bCd6jtyxbw',
    appId: '1:424900090253:android:ae981eef0cfb3f71bd45c4',
    messagingSenderId: '424900090253',
    projectId: 'aiman-hanif',
    storageBucket: 'aiman-hanif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAVPv4E53CENcseZoq-9CPyAmhENfAvY',
    appId: '1:424900090253:ios:bca747c3bd22e9a2bd45c4',
    messagingSenderId: '424900090253',
    projectId: 'aiman-hanif',
    storageBucket: 'aiman-hanif.firebasestorage.app',
    iosBundleId: 'com.tm.iprocurement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgAVPv4E53CENcseZoq-9CPyAmhENfAvY',
    appId: '1:424900090253:ios:bca747c3bd22e9a2bd45c4',
    messagingSenderId: '424900090253',
    projectId: 'aiman-hanif',
    storageBucket: 'aiman-hanif.firebasestorage.app',
    iosBundleId: 'com.tm.iprocurement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz6PhcW4rLWA8u1N5p79nRm2fqDMPmNZY',
    appId: '1:424900090253:web:8cc5ffdcaccd0d7fbd45c4',
    messagingSenderId: '424900090253',
    projectId: 'aiman-hanif',
    authDomain: 'aiman-hanif.firebaseapp.com',
    storageBucket: 'aiman-hanif.firebasestorage.app',
    measurementId: 'G-NS7H1D5C0Q',
  );

}